spring:
  redis:
    host: 192.168.41.6
    port: 6379
    database: 0
    password: 8x93I909jd90OSL
    timeout: 2000 #unit millisecond
    #lettuce client
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    #jedis client
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 5
#        min-idle: 0
