spring:
  datasource:
    db1:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 111
    db2:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/db2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 111
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
  redis:
    host: 192.168.41.6
    port: 6379
    database: 0
    password: 8x93I909jd90OSL
    timeout: 2000 #unit millisecond
    #lettuce client
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    #jedis client
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 5
#        min-idle: 0
  rabbitmq:
    host: 192.168.42.53
    username: admin
    password: 123456
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.daniel.interview.domain